data :
  input_size:
    - 252
    - 252
  image_size: 252
  BATCH_SIZE: 16
  NUM_EPOCHS: 200
  LOG_INTERVAL: 10
  EVAL_INTERVAL: 10
  CHECKPOINT_INTERVAL: 10
  
model:
  encoder: dinov2reg_vit_base_14 # 'dinov2reg_vit_small_14' or 'dinov2reg_vit_base_14' or 'dinov2reg_vit_large_14'
  INP_num: 6

  LR: 1e-3
  WEIGHT_DECAY: 0.0001
  scheduler:
    base_value: 1e-3
    final_value: 1e-4
    warmup_iters: 100
