data :
  input_size:
    - 256
    - 256
  image_size: 256
  BATCH_SIZE: 16
  NUM_EPOCHS: 1000
  LOG_INTERVAL: 20
  EVAL_INTERVAL: 20
  CHECKPOINT_INTERVAL: 20
  
model:
  teacher_model: timm_resnet34
  kwargs:
      pretrained: False
      checkpoint_path: 'MambaAD/model/pretrain/resnet34-43635321.pth'
      features_only: True      # 特徴マップだけ出力
      out_indices: [1, 2, 3]   # 取り出したい層のインデックス
      strict: False
  depths_decoder: [3, 4, 6, 3]
  scan_type: 'hilbert'
  num_direction: 8
  LR: 0.005
  WEIGHT_DECAY: 0.0001
